[package]
name = "examples"
version = "0.0.1"
edition = "2021"
publish = false

[[bin]]
name = "silentpaymentscanner"
path = "src/silentpaymentscanner.rs"

[dependencies]
silentpayments = "0.1"
bitcoin = "0.31"
secp256k1 = "0.28"
env_logger = "0.11"
log = "0.4"
bitcoinkernel = { path = ".." }
